spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: y19910811
    url: jdbc:mysql://192.168.206.130:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    check-template-location: true

mybatis:
    mapper-locations:
          classpath: /mapper/*.xml
          type-aliases-package: com.test.springbootmybatis.pojo


